name: Pull trigger test
on:
  pull_request:
      branches: 
        - 'development' 
  workflow_dispatch:

jobs:
  run-tests:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout 
       uses: actions/checkout@v3  
