name: download apks

on:
 workflow_call:
   
jobs:
  download:
      runs-on: ubuntu-latest
      steps:

        - name: Create dir
          run: |
           mkdir -p tmp/results
      
        - name: Download artifacts
          uses: actions/download-artifact@v4
          with:
            name: APKs
            path: tmp/results
            run-id: ${{ github.event.workflow_run.id }}
            github-token: ${{ github.token }}

        - name: Upload results to verify
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: APKs-new
            path: tmp/results
           
