name: Run tests
on: 
  workflow_dispatch:

jobs:
  run-tests:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout 
       uses: actions/checkout@v3
     
     - name: Set Up JDK
       uses: actions/setup-java@v3
       with:
        distribution: 'corretto'
        java-version: '11'

     - name: Change wrapper permissions
       run: chmod +x ./gradlew
       
      # Create APK Debug
     - name: Build apk debug project (APK)
       run: ./gradlew assembleDebug

     # Create APK Debug
     - name: Build apk debug test project (APK)
       run: ./gradlew assembleAndroidTest

     - name: Create dir
       run: |
          mkdir -p tmp/results

     - name: Run tests
       uses: MarathonLabs/action-test@1
       with:
        apiKey: 8qWrAp8NJZzrd0h7RkKBuVJRTVMlola60Lf9
        version: "1.0.3"
        application: app/build/outputs/apk/debug/app-debug.apk
        testApplication: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
        platform: android 
        osVersion: 13
        output: "./tmp/results"
        name: Watch_test_GHA
        device: watch    
            
     - name: Upload results
       uses: actions/upload-artifact@v4
       with:
          name: APKs-${{ inputs.task }}
          path: tmp/results

        
        
