name: Run tests
on: workflow_dispatch
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build app
      run: chmod +x ./gradlew assembleDebug assembleAndroidTest
    - name: Run tests
      uses: MarathonLabs/action-test@0
      with:
        apiKey: ${{ secrets.MARATHON_CLOUD_API_TOKEN }}
        application: app/build/outputs/apk/debug/app-debug.apk
        testApplication: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
        platform: Android
        githubToken: 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
