name: Run tests (Self-hosted) / repo
on: 
  workflow_dispatch:

jobs:
  create_apks:
    uses: ./.github/workflows/self_hosted_run.yml

  download_apks:
    if: always() && needs.create_apks.result != 'skipped' 
    uses: ./.github/workflows/download_apks.yml
