name: Run tests (Self-hosted) / repo
on: 
  workflow_dispatch:

jobs:
  create_apks:
    uses: ./.github/workflows/self_hosted_run.yml

  download_apks:
    needs: create_apks
    if: always() && needs.create_apks.result != 'skipped' 
    uses: ./.github/workflows/download_apks.yml

  use_from_flow:
    needs: create_apks
    if: always() && needs.create_apks.result != 'skipped' 
    uses: ./.github/workflows/self_hosted_run.yml
    with:
      use_artifacts_from_flow: true

  create_new:
    needs: use_from_flow
    if: always() && needs.use_from_flow.result != 'skipped' 
    uses: ./.github/workflows/self_hosted_run.yml
      
