name: Run tests (Self-hosted) / repo
on: 
  workflow_dispatch:

jobs:
  run-tests:
   runs-on: [self-hosted, win-runner]
   steps:
     - name: Checkout 
       uses: actions/checkout@v3

     - name: Get workspace envs
       shell: bash
       run: |
         echo "Github_workspace=$${{ github.workspace }}" >> $GITHUB_ENV
         echo "runner_Cache=$${{ runner.tool_cache }}" >> $GITHUB_ENV
