name: Run tests (Self-hosted)
on: 
  workflow_dispatch:

jobs:
  run-tests:
   runs-on: [self-hosted, win-runner]
   steps:
     - name: Checkout 
       uses: actions/checkout@v3
    
      # Create APK Debug
     - name: Build apk debug project (APK)
       run: ./gradlew assembleDebug

     - name: Get workspace env
       run: |
        echo "Github_workspace=$${{ github.workspace }}" >> $GITHUB_ENV

     # Create APK Debug
     - name: Build apk debug test project (APK)
       run: ./gradlew assembleAndroidTest

      
     - name: Upload results
       if: always()
       uses: actions/upload-artifact@v4
       with:
          name: APKs-${{ inputs.task }}
          path: ${{ github.workspace }}/app/build/outputs/apk
